/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        logger.info("Application started");
        logger.debug("Debugging information");
        //logger.error("An error occurred", new RuntimeException("Test error"));
    }
}
